# Generated by Django 6.0.1 on 2026-02-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lockerfile',
            name='key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
